development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: tickets_development
  pool:     5
  username: postgres
  password: 'password'
  template: template0

  
test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: tickets_test
  pool:     5
  username: postgres
  password: 'password'
  template: template0

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: tickets_production
  pool:     5
  username: postgres
  password: 'password'
  template: template0