# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 531d1df5fd353ea7814da27d6f3c85060f03573c67f780a762e0641e20594661cac97ca1a9d294e9f349dc193fab327f2f505bae9bdd7f22a7d98a7b8170f5f1

test:
  secret_key_base: 28f5413b73a589cb010f47699b24d55eb5c6ac85561fec80128a10479c3131f8c29e1884dbecb0102f7057f4f47e29c6516013b201354b4c622da2f39c4853b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
